/* 82_observation_log_patch.js
   観測ログ v5
   - voice-map.js由来の単語ID→日本語表示を追加
   - 構文タイプ称号を増量
   - 自分の定義数を localStorage から集計
   - 定義保存キー:
     megane_user_definitions_single_by_word_v1
     megane_user_definitions_by_word_v1
   - Build 1.0.3 長押し → Developer
*/
(function(){
  "use strict";

  var LOG_KEY = "megane_observation_log_v1";
  var LONG_MS = 850;

  function now(){ return new Date().toISOString(); }

  function esc(s){
    return String(s == null ? "" : s).replace(/[&<>"']/g, function(m){
      return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m];
    });
  }

  function readJson(key, fallback){
    try{ return JSON.parse(localStorage.getItem(key) || JSON.stringify(fallback)); }
    catch(e){ return fallback; }
  }

  function userDefinitionCount(){
    var count = 0;
    var seen = {};

    // 現行：1単語1定義
    var single = readJson("megane_user_definitions_single_by_word_v1", {});
    Object.keys(single || {}).forEach(function(k){
      var d = single[k] || {};
      if(d.text && String(d.text).trim()){
        seen[k] = true;
        count++;
      }
    });

    // 旧形式：1単語複数定義。移行漏れ保険。
    var old = readJson("megane_user_definitions_by_word_v1", {});
    Object.keys(old || {}).forEach(function(k){
      if(seen[k]) return;
      var arr = old[k] || [];
      if(Array.isArray(arr) && arr.some(function(x){ return x && x.text && String(x.text).trim(); })){
        count++;
      }
    });

    return count;
  }

  function userDefinitionTitle(n){
    if(n <= 0) return "読むだけ観測者";
    if(n === 1) return "初回改変者";
    if(n < 10) return "意味メモ職人";
    if(n < 30) return "意味改変者";
    if(n < 100) return "辞書汚染者";
    return "共著者";
  }

  function normalize(d){
    d = d || {};
    d.createdAt = d.createdAt || now();
    d.lastSeenAt = d.lastSeenAt || now();
    d.appOpen = Number(d.appOpen || 0);
    d.totalEvents = Number(d.totalEvents || 0);
    d.events = d.events || {};
    d.dictionary = d.dictionary || { taps:0, voices:0, words:{}, megane:{} };
    d.dictionary.words = d.dictionary.words || {};
    d.dictionary.megane = d.dictionary.megane || {};
    d.cards = d.cards || { draws:0, kinds:0, total:0 };
    d.music = d.music || { plays:0, completes:0, seconds:0, tracks:{} };
    d.music.tracks = d.music.tracks || {};
    d.conference = d.conference || { plays:0, completes:0, seconds:0 };
    d.unlocks = d.unlocks || [];
    return d;
  }

  function load(){
    try{ return normalize(JSON.parse(localStorage.getItem(LOG_KEY) || "{}") || {}); }
    catch(e){ return normalize({}); }
  }

  function save(d){
    try{ localStorage.setItem(LOG_KEY, JSON.stringify(normalize(d))); }catch(e){}
  }

  function inc(obj, key, n){
    if(!key) return;
    obj[key] = Number(obj[key] || 0) + (n || 1);
  }

  function refreshCardStats(d){
    try{
      var raw = localStorage.getItem("cardCollectionV100") || localStorage.getItem("megane_card_collection_v100") || "";
      var parsed = raw ? JSON.parse(raw) : null;
      var counts = {};
      if(Array.isArray(parsed)){
        parsed.forEach(function(x){ counts[String(x)] = (counts[String(x)] || 0) + 1; });
      }else if(parsed && typeof parsed === "object"){
        Object.keys(parsed).forEach(function(k){ counts[k] = Number(parsed[k] || 0); });
      }
      d.cards.kinds = Object.keys(counts).filter(function(k){ return Number(counts[k] || 0) > 0; }).length;
      d.cards.total = Object.keys(counts).reduce(function(a,k){ return a + Number(counts[k] || 0); }, 0);
    }catch(e){}
  }

  function observe(name, payload){
    var d = load();
    payload = payload || {};
    d.lastSeenAt = now();
    d.totalEvents++;
    inc(d.events, name, 1);

    if(name === "app.open") d.appOpen++;

    if(name === "dictionary.tap" || name === "dictionary.voice"){
      d.dictionary.voices++;
      inc(d.dictionary.words, displayWord(payload.word || payload.title || "unknown"), 1);
      inc(d.dictionary.megane, displayMegane(payload.megane || "unknown"), 1);
    }

    if(name === "card.draw"){
      d.cards.draws++;
      refreshCardStats(d);
    }

    if(name === "music.play"){
      d.music.plays++;
      inc(d.music.tracks, displayTrack(payload.title || payload.track || "unknown"), 1);
    }

    if(name === "music.complete"){
      d.music.completes++;
    }

    if(name === "music.seconds") d.music.seconds += Number(payload.seconds || 0);
    if(name === "conference.play") d.conference.plays++;
    if(name === "conference.complete") d.conference.completes++;
    if(name === "conference.seconds") d.conference.seconds += Number(payload.seconds || 0);

    if(name.indexOf("unlock.") === 0){
      var id = payload.id || name.replace(/^unlock\./,"");
      if(d.unlocks.indexOf(id) < 0) d.unlocks.push(id);
    }

    save(d);
    return d;
  }

  function displayMegane(s){
    s = String(s || "").trim();
    if(!s || s === "unknown") return "未分類";
    if(/gag|ズレア|ギャグ/i.test(s)) return "ギャグメガネ";
    if(/happy|クエリナ|ハッピー/i.test(s)) return "ハッピーメガネ";
    if(/math|ゼリス|数学/i.test(s)) return "数学メガネ";
    if(/hacker|ニクス|ハッカー/i.test(s)) return "ハッカーメガネ";
    return s;
  }

  function displayWord(s){
    s = String(s || "").trim();
    if(!s || s === "unknown") return "未分類";
    s = decodeURIComponent(s).split("/").pop().split("?")[0];
    s = s.replace(/\.(mp3|m4a|wav|ogg)$/i, "");
    s = s.replace(/_(gag|happy|math|hacker|science|medical|economy|comm|xeno|zurea|nyx|xeris|quelina|radek|milca|neia)_?\d*$/i, "");
    s = s.replace(/_\d+$/i, "");

    var map = {
      "anger": "怒り",
      "anger communication 01": "怒り",
      "anger economy 01": "怒り",
      "anger gag 01": "怒り",
      "anger hacker 01": "怒り",
      "anger happy 01": "怒り",
      "anger math 01": "怒り",
      "anger medical 01": "怒り",
      "anger science 01": "怒り",
      "anger-communication-01": "怒り",
      "anger-economy-01": "怒り",
      "anger-gag-01": "怒り",
      "anger-hacker-01": "怒り",
      "anger-happy-01": "怒り",
      "anger-math-01": "怒り",
      "anger-medical-01": "怒り",
      "anger-science-01": "怒り",
      "anger_communication_01": "怒り",
      "anger_economy_01": "怒り",
      "anger_gag_01": "怒り",
      "anger_hacker_01": "怒り",
      "anger_happy_01": "怒り",
      "anger_math_01": "怒り",
      "anger_medical_01": "怒り",
      "anger_science_01": "怒り",
      "answer": "答え",
      "answer gag 01": "答え",
      "answer hacker 01": "答え",
      "answer math 01": "答え",
      "answer-gag-01": "答え",
      "answer-hacker-01": "答え",
      "answer-math-01": "答え",
      "answer_gag_01": "答え",
      "answer_hacker_01": "答え",
      "answer_math_01": "答え",
      "anxiety": "不安",
      "anxiety communication 01": "不安",
      "anxiety economy 01": "不安",
      "anxiety gag 01": "不安",
      "anxiety hacker 01": "不安",
      "anxiety happy 01": "不安",
      "anxiety math 01": "不安",
      "anxiety medical 01": "不安",
      "anxiety science 01": "不安",
      "anxiety-communication-01": "不安",
      "anxiety-economy-01": "不安",
      "anxiety-gag-01": "不安",
      "anxiety-hacker-01": "不安",
      "anxiety-happy-01": "不安",
      "anxiety-math-01": "不安",
      "anxiety-medical-01": "不安",
      "anxiety-science-01": "不安",
      "anxiety_communication_01": "不安",
      "anxiety_economy_01": "不安",
      "anxiety_gag_01": "不安",
      "anxiety_hacker_01": "不安",
      "anxiety_happy_01": "不安",
      "anxiety_math_01": "不安",
      "anxiety_medical_01": "不安",
      "anxiety_science_01": "不安",
      "approval": "承認",
      "approval communication 01": "承認",
      "approval economy 01": "承認",
      "approval gag 01": "承認",
      "approval hacker 01": "承認",
      "approval happy 01": "承認",
      "approval math 01": "承認",
      "approval medical 01": "承認",
      "approval science 01": "承認",
      "approval-communication-01": "承認",
      "approval-economy-01": "承認",
      "approval-gag-01": "承認",
      "approval-hacker-01": "承認",
      "approval-happy-01": "承認",
      "approval-math-01": "承認",
      "approval-medical-01": "承認",
      "approval-science-01": "承認",
      "approval_communication_01": "承認",
      "approval_economy_01": "承認",
      "approval_gag_01": "承認",
      "approval_hacker_01": "承認",
      "approval_happy_01": "承認",
      "approval_math_01": "承認",
      "approval_medical_01": "承認",
      "approval_science_01": "承認",
      "betrayal": "裏切り",
      "betrayal communication 01": "裏切り",
      "betrayal economy 01": "裏切り",
      "betrayal gag 01": "裏切り",
      "betrayal hacker 01": "裏切り",
      "betrayal happy 01": "裏切り",
      "betrayal math 01": "裏切り",
      "betrayal medical 01": "裏切り",
      "betrayal science 01": "裏切り",
      "betrayal-communication-01": "裏切り",
      "betrayal-economy-01": "裏切り",
      "betrayal-gag-01": "裏切り",
      "betrayal-hacker-01": "裏切り",
      "betrayal-happy-01": "裏切り",
      "betrayal-math-01": "裏切り",
      "betrayal-medical-01": "裏切り",
      "betrayal-science-01": "裏切り",
      "betrayal_communication_01": "裏切り",
      "betrayal_economy_01": "裏切り",
      "betrayal_gag_01": "裏切り",
      "betrayal_hacker_01": "裏切り",
      "betrayal_happy_01": "裏切り",
      "betrayal_math_01": "裏切り",
      "betrayal_medical_01": "裏切り",
      "betrayal_science_01": "裏切り",
      "blood": "血",
      "blood communication 01": "血",
      "blood economy 01": "血",
      "blood gag 01": "血",
      "blood hacker 01": "血",
      "blood happy 01": "血",
      "blood math 01": "血",
      "blood medical 01": "血",
      "blood science 01": "血",
      "blood-communication-01": "血",
      "blood-economy-01": "血",
      "blood-gag-01": "血",
      "blood-hacker-01": "血",
      "blood-happy-01": "血",
      "blood-math-01": "血",
      "blood-medical-01": "血",
      "blood-science-01": "血",
      "blood_communication_01": "血",
      "blood_economy_01": "血",
      "blood_gag_01": "血",
      "blood_hacker_01": "血",
      "blood_happy_01": "血",
      "blood_math_01": "血",
      "blood_medical_01": "血",
      "blood_science_01": "血",
      "cell": "細胞",
      "cell communication 01": "細胞",
      "cell economy 01": "細胞",
      "cell gag 01": "細胞",
      "cell hacker 01": "細胞",
      "cell happy 01": "細胞",
      "cell math 01": "細胞",
      "cell medical 01": "細胞",
      "cell science 01": "細胞",
      "cell-communication-01": "細胞",
      "cell-economy-01": "細胞",
      "cell-gag-01": "細胞",
      "cell-hacker-01": "細胞",
      "cell-happy-01": "細胞",
      "cell-math-01": "細胞",
      "cell-medical-01": "細胞",
      "cell-science-01": "細胞",
      "cell_communication_01": "細胞",
      "cell_economy_01": "細胞",
      "cell_gag_01": "細胞",
      "cell_hacker_01": "細胞",
      "cell_happy_01": "細胞",
      "cell_math_01": "細胞",
      "cell_medical_01": "細胞",
      "cell_science_01": "細胞",
      "challenge": "挑戦",
      "challenge communication 01": "挑戦",
      "challenge economy 01": "挑戦",
      "challenge gag 01": "挑戦",
      "challenge hacker 01": "挑戦",
      "challenge happy 01": "挑戦",
      "challenge math 01": "挑戦",
      "challenge medical 01": "挑戦",
      "challenge science 01": "挑戦",
      "challenge-communication-01": "挑戦",
      "challenge-economy-01": "挑戦",
      "challenge-gag-01": "挑戦",
      "challenge-hacker-01": "挑戦",
      "challenge-happy-01": "挑戦",
      "challenge-math-01": "挑戦",
      "challenge-medical-01": "挑戦",
      "challenge-science-01": "挑戦",
      "challenge_communication_01": "挑戦",
      "challenge_economy_01": "挑戦",
      "challenge_gag_01": "挑戦",
      "challenge_hacker_01": "挑戦",
      "challenge_happy_01": "挑戦",
      "challenge_math_01": "挑戦",
      "challenge_medical_01": "挑戦",
      "challenge_science_01": "挑戦",
      "choice": "選択",
      "choice communication 01": "選択",
      "choice economy 01": "選択",
      "choice gag 01": "選択",
      "choice hacker 01": "選択",
      "choice happy 01": "選択",
      "choice math 01": "選択",
      "choice medical 01": "選択",
      "choice science 01": "選択",
      "choice-communication-01": "選択",
      "choice-economy-01": "選択",
      "choice-gag-01": "選択",
      "choice-hacker-01": "選択",
      "choice-happy-01": "選択",
      "choice-math-01": "選択",
      "choice-medical-01": "選択",
      "choice-science-01": "選択",
      "choice_communication_01": "選択",
      "choice_economy_01": "選択",
      "choice_gag_01": "選択",
      "choice_hacker_01": "選択",
      "choice_happy_01": "選択",
      "choice_math_01": "選択",
      "choice_medical_01": "選択",
      "choice_science_01": "選択",
      "comparison": "比較",
      "comparison communication 01": "比較",
      "comparison economy 01": "比較",
      "comparison gag 01": "比較",
      "comparison hacker 01": "比較",
      "comparison happy 01": "比較",
      "comparison math 01": "比較",
      "comparison medical 01": "比較",
      "comparison science 01": "比較",
      "comparison-communication-01": "比較",
      "comparison-economy-01": "比較",
      "comparison-gag-01": "比較",
      "comparison-hacker-01": "比較",
      "comparison-happy-01": "比較",
      "comparison-math-01": "比較",
      "comparison-medical-01": "比較",
      "comparison-science-01": "比較",
      "comparison_communication_01": "比較",
      "comparison_economy_01": "比較",
      "comparison_gag_01": "比較",
      "comparison_hacker_01": "比較",
      "comparison_happy_01": "比較",
      "comparison_math_01": "比較",
      "comparison_medical_01": "比較",
      "comparison_science_01": "比較",
      "contract": "契約",
      "contract communication 01": "契約",
      "contract economy 01": "契約",
      "contract gag 01": "契約",
      "contract hacker 01": "契約",
      "contract happy 01": "契約",
      "contract math 01": "契約",
      "contract medical 01": "契約",
      "contract science 01": "契約",
      "contract-communication-01": "契約",
      "contract-economy-01": "契約",
      "contract-gag-01": "契約",
      "contract-hacker-01": "契約",
      "contract-happy-01": "契約",
      "contract-math-01": "契約",
      "contract-medical-01": "契約",
      "contract-science-01": "契約",
      "contract_communication_01": "契約",
      "contract_economy_01": "契約",
      "contract_gag_01": "契約",
      "contract_hacker_01": "契約",
      "contract_happy_01": "契約",
      "contract_math_01": "契約",
      "contract_medical_01": "契約",
      "contract_science_01": "契約",
      "conversation": "会話",
      "conversation communication 01": "会話",
      "conversation gag 01": "会話",
      "conversation hacker 01": "会話",
      "conversation math 01": "会話",
      "conversation-communication-01": "会話",
      "conversation-gag-01": "会話",
      "conversation-hacker-01": "会話",
      "conversation-math-01": "会話",
      "conversation_communication_01": "会話",
      "conversation_gag_01": "会話",
      "conversation_hacker_01": "会話",
      "conversation_math_01": "会話",
      "courage": "勇気",
      "courage communication 01": "勇気",
      "courage economy 01": "勇気",
      "courage gag 01": "勇気",
      "courage hacker 01": "勇気",
      "courage happy 01": "勇気",
      "courage math 01": "勇気",
      "courage medical 01": "勇気",
      "courage science 01": "勇気",
      "courage-communication-01": "勇気",
      "courage-economy-01": "勇気",
      "courage-gag-01": "勇気",
      "courage-hacker-01": "勇気",
      "courage-happy-01": "勇気",
      "courage-math-01": "勇気",
      "courage-medical-01": "勇気",
      "courage-science-01": "勇気",
      "courage_communication_01": "勇気",
      "courage_economy_01": "勇気",
      "courage_gag_01": "勇気",
      "courage_hacker_01": "勇気",
      "courage_happy_01": "勇気",
      "courage_math_01": "勇気",
      "courage_medical_01": "勇気",
      "courage_science_01": "勇気",
      "credibility": "信用",
      "credibility gag 01": "信用",
      "credibility hacker 01": "信用",
      "credibility math 01": "信用",
      "credibility-gag-01": "信用",
      "credibility-hacker-01": "信用",
      "credibility-math-01": "信用",
      "credibility_gag_01": "信用",
      "credibility_hacker_01": "信用",
      "credibility_math_01": "信用",
      "death": "死",
      "death communication 01": "死",
      "death economy 01": "死",
      "death gag 01": "死",
      "death hacker 01": "死",
      "death happy 01": "死",
      "death math 01": "死",
      "death medical 01": "死",
      "death science 01": "死",
      "death-communication-01": "死",
      "death-economy-01": "死",
      "death-gag-01": "死",
      "death-hacker-01": "死",
      "death-happy-01": "死",
      "death-math-01": "死",
      "death-medical-01": "死",
      "death-science-01": "死",
      "death_communication_01": "死",
      "death_economy_01": "死",
      "death_gag_01": "死",
      "death_hacker_01": "死",
      "death_happy_01": "死",
      "death_math_01": "死",
      "death_medical_01": "死",
      "death_science_01": "死",
      "defeat": "敗北",
      "defeat communication 01": "敗北",
      "defeat economy 01": "敗北",
      "defeat gag 01": "敗北",
      "defeat hacker 01": "敗北",
      "defeat happy 01": "敗北",
      "defeat math 01": "敗北",
      "defeat medical 01": "敗北",
      "defeat science 01": "敗北",
      "defeat-communication-01": "敗北",
      "defeat-economy-01": "敗北",
      "defeat-gag-01": "敗北",
      "defeat-hacker-01": "敗北",
      "defeat-happy-01": "敗北",
      "defeat-math-01": "敗北",
      "defeat-medical-01": "敗北",
      "defeat-science-01": "敗北",
      "defeat_communication_01": "敗北",
      "defeat_economy_01": "敗北",
      "defeat_gag_01": "敗北",
      "defeat_hacker_01": "敗北",
      "defeat_happy_01": "敗北",
      "defeat_math_01": "敗北",
      "defeat_medical_01": "敗北",
      "defeat_science_01": "敗北",
      "demand": "需要",
      "demand communication 01": "需要",
      "demand economy 01": "需要",
      "demand gag 01": "需要",
      "demand hacker 01": "需要",
      "demand happy 01": "需要",
      "demand math 01": "需要",
      "demand medical 01": "需要",
      "demand science 01": "需要",
      "demand-communication-01": "需要",
      "demand-economy-01": "需要",
      "demand-gag-01": "需要",
      "demand-hacker-01": "需要",
      "demand-happy-01": "需要",
      "demand-math-01": "需要",
      "demand-medical-01": "需要",
      "demand-science-01": "需要",
      "demand_communication_01": "需要",
      "demand_economy_01": "需要",
      "demand_gag_01": "需要",
      "demand_hacker_01": "需要",
      "demand_happy_01": "需要",
      "demand_math_01": "需要",
      "demand_medical_01": "需要",
      "demand_science_01": "需要",
      "density": "密度",
      "density communication 01": "密度",
      "density economy 01": "密度",
      "density gag 01": "密度",
      "density hacker 01": "密度",
      "density happy 01": "密度",
      "density math 01": "密度",
      "density medical 01": "密度",
      "density science 01": "密度",
      "density-communication-01": "密度",
      "density-economy-01": "密度",
      "density-gag-01": "密度",
      "density-hacker-01": "密度",
      "density-happy-01": "密度",
      "density-math-01": "密度",
      "density-medical-01": "密度",
      "density-science-01": "密度",
      "density_communication_01": "密度",
      "density_economy_01": "密度",
      "density_gag_01": "密度",
      "density_hacker_01": "密度",
      "density_happy_01": "密度",
      "density_math_01": "密度",
      "density_medical_01": "密度",
      "density_science_01": "密度",
      "distance": "距離",
      "distance gag 01": "距離",
      "distance hacker 01": "距離",
      "distance math 01": "距離",
      "distance-gag-01": "距離",
      "distance-hacker-01": "距離",
      "distance-math-01": "距離",
      "distance_gag_01": "距離",
      "distance_hacker_01": "距離",
      "distance_math_01": "距離",
      "dream": "夢",
      "dream gag 01": "夢",
      "dream hacker 01": "夢",
      "dream math 01": "夢",
      "dream-gag-01": "夢",
      "dream-hacker-01": "夢",
      "dream-math-01": "夢",
      "dream_gag_01": "夢",
      "dream_hacker_01": "夢",
      "dream_math_01": "夢",
      "empathy": "共感",
      "empathy gag 01": "共感",
      "empathy hacker 01": "共感",
      "empathy math 01": "共感",
      "empathy-gag-01": "共感",
      "empathy-hacker-01": "共感",
      "empathy-math-01": "共感",
      "empathy_gag_01": "共感",
      "empathy_hacker_01": "共感",
      "empathy_math_01": "共感",
      "exchange": "交換",
      "exchange communication 01": "交換",
      "exchange economy 01": "交換",
      "exchange gag 01": "交換",
      "exchange hacker 01": "交換",
      "exchange happy 01": "交換",
      "exchange math 01": "交換",
      "exchange medical 01": "交換",
      "exchange science 01": "交換",
      "exchange-communication-01": "交換",
      "exchange-economy-01": "交換",
      "exchange-gag-01": "交換",
      "exchange-hacker-01": "交換",
      "exchange-happy-01": "交換",
      "exchange-math-01": "交換",
      "exchange-medical-01": "交換",
      "exchange-science-01": "交換",
      "exchange_communication_01": "交換",
      "exchange_economy_01": "交換",
      "exchange_gag_01": "交換",
      "exchange_hacker_01": "交換",
      "exchange_happy_01": "交換",
      "exchange_math_01": "交換",
      "exchange_medical_01": "交換",
      "exchange_science_01": "交換",
      "excitement": "わくわく",
      "excitement communication 01": "わくわく",
      "excitement economy 01": "わくわく",
      "excitement gag 01": "わくわく",
      "excitement hacker 01": "わくわく",
      "excitement happy 01": "わくわく",
      "excitement math 01": "わくわく",
      "excitement medical 01": "わくわく",
      "excitement science 01": "わくわく",
      "excitement-communication-01": "わくわく",
      "excitement-economy-01": "わくわく",
      "excitement-gag-01": "わくわく",
      "excitement-hacker-01": "わくわく",
      "excitement-happy-01": "わくわく",
      "excitement-math-01": "わくわく",
      "excitement-medical-01": "わくわく",
      "excitement-science-01": "わくわく",
      "excitement_communication_01": "わくわく",
      "excitement_economy_01": "わくわく",
      "excitement_gag_01": "わくわく",
      "excitement_hacker_01": "わくわく",
      "excitement_happy_01": "わくわく",
      "excitement_math_01": "わくわく",
      "excitement_medical_01": "わくわく",
      "excitement_science_01": "わくわく",
      "expectation": "期待",
      "expectation communication 01": "期待",
      "expectation economy 01": "期待",
      "expectation gag 01": "期待",
      "expectation hacker 01": "期待",
      "expectation happy 01": "期待",
      "expectation math 01": "期待",
      "expectation medical 01": "期待",
      "expectation science 01": "期待",
      "expectation-communication-01": "期待",
      "expectation-economy-01": "期待",
      "expectation-gag-01": "期待",
      "expectation-hacker-01": "期待",
      "expectation-happy-01": "期待",
      "expectation-math-01": "期待",
      "expectation-medical-01": "期待",
      "expectation-science-01": "期待",
      "expectation_communication_01": "期待",
      "expectation_economy_01": "期待",
      "expectation_gag_01": "期待",
      "expectation_hacker_01": "期待",
      "expectation_happy_01": "期待",
      "expectation_math_01": "期待",
      "expectation_medical_01": "期待",
      "expectation_science_01": "期待",
      "favorite": "お気に入り",
      "favorite communication 01": "お気に入り",
      "favorite economy 01": "お気に入り",
      "favorite gag 01": "お気に入り",
      "favorite hacker 01": "お気に入り",
      "favorite happy 01": "お気に入り",
      "favorite math 01": "お気に入り",
      "favorite medical 01": "お気に入り",
      "favorite science 01": "お気に入り",
      "favorite-communication-01": "お気に入り",
      "favorite-economy-01": "お気に入り",
      "favorite-gag-01": "お気に入り",
      "favorite-hacker-01": "お気に入り",
      "favorite-happy-01": "お気に入り",
      "favorite-math-01": "お気に入り",
      "favorite-medical-01": "お気に入り",
      "favorite-science-01": "お気に入り",
      "favorite_communication_01": "お気に入り",
      "favorite_economy_01": "お気に入り",
      "favorite_gag_01": "お気に入り",
      "favorite_hacker_01": "お気に入り",
      "favorite_happy_01": "お気に入り",
      "favorite_math_01": "お気に入り",
      "favorite_medical_01": "お気に入り",
      "favorite_science_01": "お気に入り",
      "fear": "恐怖",
      "fear communication 01": "恐怖",
      "fear economy 01": "恐怖",
      "fear gag 01": "恐怖",
      "fear hacker 01": "恐怖",
      "fear happy 01": "恐怖",
      "fear math 01": "恐怖",
      "fear medical 01": "恐怖",
      "fear science 01": "恐怖",
      "fear-communication-01": "恐怖",
      "fear-economy-01": "恐怖",
      "fear-gag-01": "恐怖",
      "fear-hacker-01": "恐怖",
      "fear-happy-01": "恐怖",
      "fear-math-01": "恐怖",
      "fear-medical-01": "恐怖",
      "fear-science-01": "恐怖",
      "fear_communication_01": "恐怖",
      "fear_economy_01": "恐怖",
      "fear_gag_01": "恐怖",
      "fear_hacker_01": "恐怖",
      "fear_happy_01": "恐怖",
      "fear_math_01": "恐怖",
      "fear_medical_01": "恐怖",
      "fear_science_01": "恐怖",
      "flow": "流れ",
      "flow gag 01": "流れ",
      "flow hacker 01": "流れ",
      "flow math 01": "流れ",
      "flow-gag-01": "流れ",
      "flow-hacker-01": "流れ",
      "flow-math-01": "流れ",
      "flow_gag_01": "流れ",
      "flow_hacker_01": "流れ",
      "flow_math_01": "流れ",
      "freedom": "自由",
      "freedom communication 01": "自由",
      "freedom economy 01": "自由",
      "freedom gag 01": "自由",
      "freedom hacker 01": "自由",
      "freedom happy 01": "自由",
      "freedom math 01": "自由",
      "freedom medical 01": "自由",
      "freedom science 01": "自由",
      "freedom-communication-01": "自由",
      "freedom-economy-01": "自由",
      "freedom-gag-01": "自由",
      "freedom-hacker-01": "自由",
      "freedom-happy-01": "自由",
      "freedom-math-01": "自由",
      "freedom-medical-01": "自由",
      "freedom-science-01": "自由",
      "freedom_communication_01": "自由",
      "freedom_economy_01": "自由",
      "freedom_gag_01": "自由",
      "freedom_hacker_01": "自由",
      "freedom_happy_01": "自由",
      "freedom_math_01": "自由",
      "freedom_medical_01": "自由",
      "freedom_science_01": "自由",
      "friend": "友達",
      "friend communication 01": "友達",
      "friend economy 01": "友達",
      "friend gag 01": "友達",
      "friend hacker 01": "友達",
      "friend happy 01": "友達",
      "friend math 01": "友達",
      "friend medical 01": "友達",
      "friend science 01": "友達",
      "friend-communication-01": "友達",
      "friend-economy-01": "友達",
      "friend-gag-01": "友達",
      "friend-hacker-01": "友達",
      "friend-happy-01": "友達",
      "friend-math-01": "友達",
      "friend-medical-01": "友達",
      "friend-science-01": "友達",
      "friend_communication_01": "友達",
      "friend_economy_01": "友達",
      "friend_gag_01": "友達",
      "friend_hacker_01": "友達",
      "friend_happy_01": "友達",
      "friend_math_01": "友達",
      "friend_medical_01": "友達",
      "friend_science_01": "友達",
      "future": "未来",
      "future gag 01": "未来",
      "future hacker 01": "未来",
      "future math 01": "未来",
      "future-gag-01": "未来",
      "future-hacker-01": "未来",
      "future-math-01": "未来",
      "future_gag_01": "未来",
      "future_hacker_01": "未来",
      "future_math_01": "未来",
      "growth": "成長",
      "growth gag 01": "成長",
      "growth hacker 01": "成長",
      "growth math 01": "成長",
      "growth-gag-01": "成長",
      "growth-hacker-01": "成長",
      "growth-math-01": "成長",
      "growth_gag_01": "成長",
      "growth_hacker_01": "成長",
      "growth_math_01": "成長",
      "healing": "治癒",
      "healing gag 01": "治癒",
      "healing hacker 01": "治癒",
      "healing math 01": "治癒",
      "healing-gag-01": "治癒",
      "healing-hacker-01": "治癒",
      "healing-math-01": "治癒",
      "healing_gag_01": "治癒",
      "healing_hacker_01": "治癒",
      "healing_math_01": "治癒",
      "homework": "宿題",
      "homework communication 01": "宿題",
      "homework economy 01": "宿題",
      "homework gag 01": "宿題",
      "homework hacker 01": "宿題",
      "homework happy 01": "宿題",
      "homework math 01": "宿題",
      "homework medical 01": "宿題",
      "homework science 01": "宿題",
      "homework-communication-01": "宿題",
      "homework-economy-01": "宿題",
      "homework-gag-01": "宿題",
      "homework-hacker-01": "宿題",
      "homework-happy-01": "宿題",
      "homework-math-01": "宿題",
      "homework-medical-01": "宿題",
      "homework-science-01": "宿題",
      "homework_communication_01": "宿題",
      "homework_economy_01": "宿題",
      "homework_gag_01": "宿題",
      "homework_hacker_01": "宿題",
      "homework_happy_01": "宿題",
      "homework_math_01": "宿題",
      "homework_medical_01": "宿題",
      "homework_science_01": "宿題",
      "imagination": "想像",
      "imagination communication 01": "想像",
      "imagination economy 01": "想像",
      "imagination gag 01": "想像",
      "imagination hacker 01": "想像",
      "imagination happy 01": "想像",
      "imagination math 01": "想像",
      "imagination medical 01": "想像",
      "imagination science 01": "想像",
      "imagination-communication-01": "想像",
      "imagination-economy-01": "想像",
      "imagination-gag-01": "想像",
      "imagination-hacker-01": "想像",
      "imagination-happy-01": "想像",
      "imagination-math-01": "想像",
      "imagination-medical-01": "想像",
      "imagination-science-01": "想像",
      "imagination_communication_01": "想像",
      "imagination_economy_01": "想像",
      "imagination_gag_01": "想像",
      "imagination_hacker_01": "想像",
      "imagination_happy_01": "想像",
      "imagination_math_01": "想像",
      "imagination_medical_01": "想像",
      "imagination_science_01": "想像",
      "immunity": "免疫",
      "immunity communication 01": "免疫",
      "immunity economy 01": "免疫",
      "immunity gag 01": "免疫",
      "immunity hacker 01": "免疫",
      "immunity happy 01": "免疫",
      "immunity math 01": "免疫",
      "immunity medical 01": "免疫",
      "immunity science 01": "免疫",
      "immunity-communication-01": "免疫",
      "immunity-economy-01": "免疫",
      "immunity-gag-01": "免疫",
      "immunity-hacker-01": "免疫",
      "immunity-happy-01": "免疫",
      "immunity-math-01": "免疫",
      "immunity-medical-01": "免疫",
      "immunity-science-01": "免疫",
      "immunity_communication_01": "免疫",
      "immunity_economy_01": "免疫",
      "immunity_gag_01": "免疫",
      "immunity_hacker_01": "免疫",
      "immunity_happy_01": "免疫",
      "immunity_math_01": "免疫",
      "immunity_medical_01": "免疫",
      "immunity_science_01": "免疫",
      "investment": "投資",
      "investment communication 01": "投資",
      "investment economy 01": "投資",
      "investment gag 01": "投資",
      "investment hacker 01": "投資",
      "investment happy 01": "投資",
      "investment math 01": "投資",
      "investment medical 01": "投資",
      "investment science 01": "投資",
      "investment-communication-01": "投資",
      "investment-economy-01": "投資",
      "investment-gag-01": "投資",
      "investment-hacker-01": "投資",
      "investment-happy-01": "投資",
      "investment-math-01": "投資",
      "investment-medical-01": "投資",
      "investment-science-01": "投資",
      "investment_communication_01": "投資",
      "investment_economy_01": "投資",
      "investment_gag_01": "投資",
      "investment_hacker_01": "投資",
      "investment_happy_01": "投資",
      "investment_math_01": "投資",
      "investment_medical_01": "投資",
      "investment_science_01": "投資",
      "joy": "喜び",
      "joy communication 01": "喜び",
      "joy economy 01": "喜び",
      "joy gag 01": "喜び",
      "joy hacker 01": "喜び",
      "joy happy 01": "喜び",
      "joy math 01": "喜び",
      "joy medical 01": "喜び",
      "joy science 01": "喜び",
      "joy-communication-01": "喜び",
      "joy-economy-01": "喜び",
      "joy-gag-01": "喜び",
      "joy-hacker-01": "喜び",
      "joy-happy-01": "喜び",
      "joy-math-01": "喜び",
      "joy-medical-01": "喜び",
      "joy-science-01": "喜び",
      "joy_communication_01": "喜び",
      "joy_economy_01": "喜び",
      "joy_gag_01": "喜び",
      "joy_hacker_01": "喜び",
      "joy_happy_01": "喜び",
      "joy_math_01": "喜び",
      "joy_medical_01": "喜び",
      "joy_science_01": "喜び",
      "jump": "跳ね",
      "jump communication 01": "跳ね",
      "jump economy 01": "跳ね",
      "jump gag 01": "跳ね",
      "jump hacker 01": "跳ね",
      "jump happy 01": "跳ね",
      "jump math 01": "跳ね",
      "jump medical 01": "跳ね",
      "jump science 01": "跳ね",
      "jump-communication-01": "跳ね",
      "jump-economy-01": "跳ね",
      "jump-gag-01": "跳ね",
      "jump-hacker-01": "跳ね",
      "jump-happy-01": "跳ね",
      "jump-math-01": "跳ね",
      "jump-medical-01": "跳ね",
      "jump-science-01": "跳ね",
      "jump_communication_01": "跳ね",
      "jump_economy_01": "跳ね",
      "jump_gag_01": "跳ね",
      "jump_hacker_01": "跳ね",
      "jump_happy_01": "跳ね",
      "jump_math_01": "跳ね",
      "jump_medical_01": "跳ね",
      "jump_science_01": "跳ね",
      "justice": "正義",
      "justice communication 01": "正義",
      "justice economy 01": "正義",
      "justice gag 01": "正義",
      "justice hacker 01": "正義",
      "justice happy 01": "正義",
      "justice math 01": "正義",
      "justice medical 01": "正義",
      "justice science 01": "正義",
      "justice-communication-01": "正義",
      "justice-economy-01": "正義",
      "justice-gag-01": "正義",
      "justice-hacker-01": "正義",
      "justice-happy-01": "正義",
      "justice-math-01": "正義",
      "justice-medical-01": "正義",
      "justice-science-01": "正義",
      "justice_communication_01": "正義",
      "justice_economy_01": "正義",
      "justice_gag_01": "正義",
      "justice_hacker_01": "正義",
      "justice_happy_01": "正義",
      "justice_math_01": "正義",
      "justice_medical_01": "正義",
      "justice_science_01": "正義",
      "kindness": "優しさ",
      "kindness communication 01": "優しさ",
      "kindness economy 01": "優しさ",
      "kindness gag 01": "優しさ",
      "kindness hacker 01": "優しさ",
      "kindness happy 01": "優しさ",
      "kindness math 01": "優しさ",
      "kindness medical 01": "優しさ",
      "kindness science 01": "優しさ",
      "kindness-communication-01": "優しさ",
      "kindness-economy-01": "優しさ",
      "kindness-gag-01": "優しさ",
      "kindness-hacker-01": "優しさ",
      "kindness-happy-01": "優しさ",
      "kindness-math-01": "優しさ",
      "kindness-medical-01": "優しさ",
      "kindness-science-01": "優しさ",
      "kindness_communication_01": "優しさ",
      "kindness_economy_01": "優しさ",
      "kindness_gag_01": "優しさ",
      "kindness_hacker_01": "優しさ",
      "kindness_happy_01": "優しさ",
      "kindness_math_01": "優しさ",
      "kindness_medical_01": "優しさ",
      "kindness_science_01": "優しさ",
      "laugh": "笑い",
      "laugh gag 01": "笑い",
      "laugh hacker 01": "笑い",
      "laugh math 01": "笑い",
      "laugh-gag-01": "笑い",
      "laugh-hacker-01": "笑い",
      "laugh-math-01": "笑い",
      "laugh_gag_01": "笑い",
      "laugh_hacker_01": "笑い",
      "laugh_math_01": "笑い",
      "laughter": "笑い",
      "level": "レベル",
      "level communication 01": "レベル",
      "level economy 01": "レベル",
      "level gag 01": "レベル",
      "level hacker 01": "レベル",
      "level happy 01": "レベル",
      "level math 01": "レベル",
      "level medical 01": "レベル",
      "level science 01": "レベル",
      "level-communication-01": "レベル",
      "level-economy-01": "レベル",
      "level-gag-01": "レベル",
      "level-hacker-01": "レベル",
      "level-happy-01": "レベル",
      "level-math-01": "レベル",
      "level-medical-01": "レベル",
      "level-science-01": "レベル",
      "level_communication_01": "レベル",
      "level_economy_01": "レベル",
      "level_gag_01": "レベル",
      "level_hacker_01": "レベル",
      "level_happy_01": "レベル",
      "level_math_01": "レベル",
      "level_medical_01": "レベル",
      "level_science_01": "レベル",
      "life": "命",
      "life gag 01": "命",
      "life hacker 01": "命",
      "life math 01": "命",
      "life-gag-01": "命",
      "life-hacker-01": "命",
      "life-math-01": "命",
      "life_gag_01": "命",
      "life_hacker_01": "命",
      "life_math_01": "命",
      "light": "光",
      "light gag 01": "光",
      "light hacker 01": "光",
      "light math 01": "光",
      "light-gag-01": "光",
      "light-hacker-01": "光",
      "light-math-01": "光",
      "light_gag_01": "光",
      "light_hacker_01": "光",
      "light_math_01": "光",
      "like": "好き",
      "like communication 01": "好き",
      "like economy 01": "好き",
      "like gag 01": "好き",
      "like hacker 01": "好き",
      "like happy 01": "好き",
      "like math 01": "好き",
      "like medical 01": "好き",
      "like science 01": "好き",
      "like-communication-01": "好き",
      "like-economy-01": "好き",
      "like-gag-01": "好き",
      "like-hacker-01": "好き",
      "like-happy-01": "好き",
      "like-math-01": "好き",
      "like-medical-01": "好き",
      "like-science-01": "好き",
      "like_communication_01": "好き",
      "like_economy_01": "好き",
      "like_gag_01": "好き",
      "like_hacker_01": "好き",
      "like_happy_01": "好き",
      "like_math_01": "好き",
      "like_medical_01": "好き",
      "like_science_01": "好き",
      "loneliness": "孤独",
      "loneliness gag 01": "孤独",
      "loneliness hacker 01": "孤独",
      "loneliness math 01": "孤独",
      "loneliness-gag-01": "孤独",
      "loneliness-hacker-01": "孤独",
      "loneliness-math-01": "孤独",
      "loneliness_gag_01": "孤独",
      "loneliness_hacker_01": "孤独",
      "loneliness_math_01": "孤独",
      "love": "愛",
      "love communication 01": "愛",
      "love economy 01": "愛",
      "love gag 01": "愛",
      "love hacker 01": "愛",
      "love happy 01": "愛",
      "love math 01": "愛",
      "love medical 01": "愛",
      "love science 01": "愛",
      "love-communication-01": "愛",
      "love-economy-01": "愛",
      "love-gag-01": "愛",
      "love-hacker-01": "愛",
      "love-happy-01": "愛",
      "love-math-01": "愛",
      "love-medical-01": "愛",
      "love-science-01": "愛",
      "love_communication_01": "愛",
      "love_economy_01": "愛",
      "love_gag_01": "愛",
      "love_hacker_01": "愛",
      "love_happy_01": "愛",
      "love_math_01": "愛",
      "love_medical_01": "愛",
      "love_science_01": "愛",
      "market": "市場",
      "market communication 01": "市場",
      "market economy 01": "市場",
      "market gag 01": "市場",
      "market hacker 01": "市場",
      "market happy 01": "市場",
      "market math 01": "市場",
      "market medical 01": "市場",
      "market science 01": "市場",
      "market-communication-01": "市場",
      "market-economy-01": "市場",
      "market-gag-01": "市場",
      "market-hacker-01": "市場",
      "market-happy-01": "市場",
      "market-math-01": "市場",
      "market-medical-01": "市場",
      "market-science-01": "市場",
      "market_communication_01": "市場",
      "market_economy_01": "市場",
      "market_gag_01": "市場",
      "market_hacker_01": "市場",
      "market_happy_01": "市場",
      "market_math_01": "市場",
      "market_medical_01": "市場",
      "market_science_01": "市場",
      "matter": "物質",
      "matter communication 01": "物質",
      "matter economy 01": "物質",
      "matter gag 01": "物質",
      "matter hacker 01": "物質",
      "matter happy 01": "物質",
      "matter math 01": "物質",
      "matter medical 01": "物質",
      "matter science 01": "物質",
      "matter-communication-01": "物質",
      "matter-economy-01": "物質",
      "matter-gag-01": "物質",
      "matter-hacker-01": "物質",
      "matter-happy-01": "物質",
      "matter-math-01": "物質",
      "matter-medical-01": "物質",
      "matter-science-01": "物質",
      "matter_communication_01": "物質",
      "matter_economy_01": "物質",
      "matter_gag_01": "物質",
      "matter_hacker_01": "物質",
      "matter_happy_01": "物質",
      "matter_math_01": "物質",
      "matter_medical_01": "物質",
      "matter_science_01": "物質",
      "meaning": "意味",
      "meaning communication 01": "意味",
      "meaning economy 01": "意味",
      "meaning gag 01": "意味",
      "meaning hacker 01": "意味",
      "meaning happy 01": "意味",
      "meaning math 01": "意味",
      "meaning medical 01": "意味",
      "meaning science 01": "意味",
      "meaning-communication-01": "意味",
      "meaning-economy-01": "意味",
      "meaning-gag-01": "意味",
      "meaning-hacker-01": "意味",
      "meaning-happy-01": "意味",
      "meaning-math-01": "意味",
      "meaning-medical-01": "意味",
      "meaning-science-01": "意味",
      "meaning_communication_01": "意味",
      "meaning_economy_01": "意味",
      "meaning_gag_01": "意味",
      "meaning_hacker_01": "意味",
      "meaning_happy_01": "意味",
      "meaning_math_01": "意味",
      "meaning_medical_01": "意味",
      "meaning_science_01": "意味",
      "melon pan": "メロンパン",
      "melon pan communication 01": "メロンパン",
      "melon pan economy 01": "メロンパン",
      "melon pan gag 01": "メロンパン",
      "melon pan hacker 01": "メロンパン",
      "melon pan happy 01": "メロンパン",
      "melon pan math 01": "メロンパン",
      "melon pan medical 01": "メロンパン",
      "melon pan science 01": "メロンパン",
      "melon-pan": "メロンパン",
      "melon-pan-communication-01": "メロンパン",
      "melon-pan-economy-01": "メロンパン",
      "melon-pan-gag-01": "メロンパン",
      "melon-pan-hacker-01": "メロンパン",
      "melon-pan-happy-01": "メロンパン",
      "melon-pan-math-01": "メロンパン",
      "melon-pan-medical-01": "メロンパン",
      "melon-pan-science-01": "メロンパン",
      "melon_pan": "メロンパン",
      "melon_pan_communication_01": "メロンパン",
      "melon_pan_economy_01": "メロンパン",
      "melon_pan_gag_01": "メロンパン",
      "melon_pan_hacker_01": "メロンパン",
      "melon_pan_happy_01": "メロンパン",
      "melon_pan_math_01": "メロンパン",
      "melon_pan_medical_01": "メロンパン",
      "melon_pan_science_01": "メロンパン",
      "memory": "記憶",
      "memory communication 01": "記憶",
      "memory economy 01": "記憶",
      "memory gag 01": "記憶",
      "memory hacker 01": "記憶",
      "memory happy 01": "記憶",
      "memory math 01": "記憶",
      "memory medical 01": "記憶",
      "memory science 01": "記憶",
      "memory-communication-01": "記憶",
      "memory-economy-01": "記憶",
      "memory-gag-01": "記憶",
      "memory-hacker-01": "記憶",
      "memory-happy-01": "記憶",
      "memory-math-01": "記憶",
      "memory-medical-01": "記憶",
      "memory-science-01": "記憶",
      "memory_communication_01": "記憶",
      "memory_economy_01": "記憶",
      "memory_gag_01": "記憶",
      "memory_hacker_01": "記憶",
      "memory_happy_01": "記憶",
      "memory_math_01": "記憶",
      "memory_medical_01": "記憶",
      "memory_science_01": "記憶",
      "misunderstanding": "誤解",
      "misunderstanding gag 01": "誤解",
      "misunderstanding hacker 01": "誤解",
      "misunderstanding math 01": "誤解",
      "misunderstanding-gag-01": "誤解",
      "misunderstanding-hacker-01": "誤解",
      "misunderstanding-math-01": "誤解",
      "misunderstanding_gag_01": "誤解",
      "misunderstanding_hacker_01": "誤解",
      "misunderstanding_math_01": "誤解",
      "mp3ファイル名（拡張子なし）": "単語",
      "name": "名前",
      "name gag 01": "名前",
      "name hacker 01": "名前",
      "name math 01": "名前",
      "name-gag-01": "名前",
      "name-hacker-01": "名前",
      "name-math-01": "名前",
      "name_gag_01": "名前",
      "name_hacker_01": "名前",
      "name_math_01": "名前",
      "normal": "普通",
      "normal communication 01": "普通",
      "normal economy 01": "普通",
      "normal gag 01": "普通",
      "normal hacker 01": "普通",
      "normal happy 01": "普通",
      "normal math 01": "普通",
      "normal medical 01": "普通",
      "normal science 01": "普通",
      "normal-communication-01": "普通",
      "normal-economy-01": "普通",
      "normal-gag-01": "普通",
      "normal-hacker-01": "普通",
      "normal-happy-01": "普通",
      "normal-math-01": "普通",
      "normal-medical-01": "普通",
      "normal-science-01": "普通",
      "normal_communication_01": "普通",
      "normal_economy_01": "普通",
      "normal_gag_01": "普通",
      "normal_hacker_01": "普通",
      "normal_happy_01": "普通",
      "normal_math_01": "普通",
      "normal_medical_01": "普通",
      "normal_science_01": "普通",
      "observation": "観測",
      "observe": "観測",
      "observe communication 01": "観測",
      "observe economy 01": "観測",
      "observe gag 01": "観測",
      "observe hacker 01": "観測",
      "observe happy 01": "観測",
      "observe math 01": "観測",
      "observe medical 01": "観測",
      "observe science 01": "観測",
      "observe-communication-01": "観測",
      "observe-economy-01": "観測",
      "observe-gag-01": "観測",
      "observe-hacker-01": "観測",
      "observe-happy-01": "観測",
      "observe-math-01": "観測",
      "observe-medical-01": "観測",
      "observe-science-01": "観測",
      "observe_communication_01": "観測",
      "observe_economy_01": "観測",
      "observe_gag_01": "観測",
      "observe_hacker_01": "観測",
      "observe_happy_01": "観測",
      "observe_math_01": "観測",
      "observe_medical_01": "観測",
      "observe_science_01": "観測",
      "obvious": "当たり前",
      "obvious communication 01": "当たり前",
      "obvious economy 01": "当たり前",
      "obvious gag 01": "当たり前",
      "obvious hacker 01": "当たり前",
      "obvious happy 01": "当たり前",
      "obvious math 01": "当たり前",
      "obvious medical 01": "当たり前",
      "obvious science 01": "当たり前",
      "obvious-communication-01": "当たり前",
      "obvious-economy-01": "当たり前",
      "obvious-gag-01": "当たり前",
      "obvious-hacker-01": "当たり前",
      "obvious-happy-01": "当たり前",
      "obvious-math-01": "当たり前",
      "obvious-medical-01": "当たり前",
      "obvious-science-01": "当たり前",
      "obvious_communication_01": "当たり前",
      "obvious_economy_01": "当たり前",
      "obvious_gag_01": "当たり前",
      "obvious_hacker_01": "当たり前",
      "obvious_happy_01": "当たり前",
      "obvious_math_01": "当たり前",
      "obvious_medical_01": "当たり前",
      "obvious_science_01": "当たり前",
      "pain": "痛み",
      "pain gag 01": "痛み",
      "pain hacker 01": "痛み",
      "pain math 01": "痛み",
      "pain-gag-01": "痛み",
      "pain-hacker-01": "痛み",
      "pain-math-01": "痛み",
      "pain_gag_01": "痛み",
      "pain_hacker_01": "痛み",
      "pain_math_01": "痛み",
      "past": "過去",
      "past communication 01": "過去",
      "past economy 01": "過去",
      "past gag 01": "過去",
      "past hacker 01": "過去",
      "past happy 01": "過去",
      "past math 01": "過去",
      "past medical 01": "過去",
      "past science 01": "過去",
      "past-communication-01": "過去",
      "past-economy-01": "過去",
      "past-gag-01": "過去",
      "past-hacker-01": "過去",
      "past-happy-01": "過去",
      "past-math-01": "過去",
      "past-medical-01": "過去",
      "past-science-01": "過去",
      "past_communication_01": "過去",
      "past_economy_01": "過去",
      "past_gag_01": "過去",
      "past_hacker_01": "過去",
      "past_happy_01": "過去",
      "past_math_01": "過去",
      "past_medical_01": "過去",
      "past_science_01": "過去",
      "present": "現在",
      "present communication 01": "現在",
      "present economy 01": "現在",
      "present gag 01": "現在",
      "present hacker 01": "現在",
      "present happy 01": "現在",
      "present math 01": "現在",
      "present medical 01": "現在",
      "present science 01": "現在",
      "present-communication-01": "現在",
      "present-economy-01": "現在",
      "present-gag-01": "現在",
      "present-hacker-01": "現在",
      "present-happy-01": "現在",
      "present-math-01": "現在",
      "present-medical-01": "現在",
      "present-science-01": "現在",
      "present_communication_01": "現在",
      "present_economy_01": "現在",
      "present_gag_01": "現在",
      "present_hacker_01": "現在",
      "present_happy_01": "現在",
      "present_math_01": "現在",
      "present_medical_01": "現在",
      "present_science_01": "現在",
      "price": "価格",
      "price communication 01": "価格",
      "price economy 01": "価格",
      "price gag 01": "価格",
      "price hacker 01": "価格",
      "price happy 01": "価格",
      "price math 01": "価格",
      "price medical 01": "価格",
      "price science 01": "価格",
      "price-communication-01": "価格",
      "price-economy-01": "価格",
      "price-gag-01": "価格",
      "price-hacker-01": "価格",
      "price-happy-01": "価格",
      "price-math-01": "価格",
      "price-medical-01": "価格",
      "price-science-01": "価格",
      "price_communication_01": "価格",
      "price_economy_01": "価格",
      "price_gag_01": "価格",
      "price_hacker_01": "価格",
      "price_happy_01": "価格",
      "price_math_01": "価格",
      "price_medical_01": "価格",
      "price_science_01": "価格",
      "probability": "確率",
      "probability gag 01": "確率",
      "probability hacker 01": "確率",
      "probability math 01": "確率",
      "probability-gag-01": "確率",
      "probability-hacker-01": "確率",
      "probability-math-01": "確率",
      "probability_gag_01": "確率",
      "probability_hacker_01": "確率",
      "probability_math_01": "確率",
      "prohibition": "禁止",
      "prohibition communication 01": "禁止",
      "prohibition economy 01": "禁止",
      "prohibition gag 01": "禁止",
      "prohibition hacker 01": "禁止",
      "prohibition happy 01": "禁止",
      "prohibition math 01": "禁止",
      "prohibition medical 01": "禁止",
      "prohibition science 01": "禁止",
      "prohibition-communication-01": "禁止",
      "prohibition-economy-01": "禁止",
      "prohibition-gag-01": "禁止",
      "prohibition-hacker-01": "禁止",
      "prohibition-happy-01": "禁止",
      "prohibition-math-01": "禁止",
      "prohibition-medical-01": "禁止",
      "prohibition-science-01": "禁止",
      "prohibition_communication_01": "禁止",
      "prohibition_economy_01": "禁止",
      "prohibition_gag_01": "禁止",
      "prohibition_hacker_01": "禁止",
      "prohibition_happy_01": "禁止",
      "prohibition_math_01": "禁止",
      "prohibition_medical_01": "禁止",
      "prohibition_science_01": "禁止",
      "promise": "約束",
      "promise communication 01": "約束",
      "promise economy 01": "約束",
      "promise gag 01": "約束",
      "promise hacker 01": "約束",
      "promise happy 01": "約束",
      "promise math 01": "約束",
      "promise medical 01": "約束",
      "promise science 01": "約束",
      "promise-communication-01": "約束",
      "promise-economy-01": "約束",
      "promise-gag-01": "約束",
      "promise-hacker-01": "約束",
      "promise-happy-01": "約束",
      "promise-math-01": "約束",
      "promise-medical-01": "約束",
      "promise-science-01": "約束",
      "promise_communication_01": "約束",
      "promise_economy_01": "約束",
      "promise_gag_01": "約束",
      "promise_hacker_01": "約束",
      "promise_happy_01": "約束",
      "promise_math_01": "約束",
      "promise_medical_01": "約束",
      "promise_science_01": "約束",
      "question": "質問",
      "question gag 01": "質問",
      "question hacker 01": "質問",
      "question math 01": "質問",
      "question-gag-01": "質問",
      "question-hacker-01": "質問",
      "question-math-01": "質問",
      "question_gag_01": "質問",
      "question_hacker_01": "質問",
      "question_math_01": "質問",
      "regeneration": "再生",
      "regeneration communication 01": "再生",
      "regeneration economy 01": "再生",
      "regeneration gag 01": "再生",
      "regeneration hacker 01": "再生",
      "regeneration happy 01": "再生",
      "regeneration math 01": "再生",
      "regeneration medical 01": "再生",
      "regeneration science 01": "再生",
      "regeneration-communication-01": "再生",
      "regeneration-economy-01": "再生",
      "regeneration-gag-01": "再生",
      "regeneration-hacker-01": "再生",
      "regeneration-happy-01": "再生",
      "regeneration-math-01": "再生",
      "regeneration-medical-01": "再生",
      "regeneration-science-01": "再生",
      "regeneration_communication_01": "再生",
      "regeneration_economy_01": "再生",
      "regeneration_gag_01": "再生",
      "regeneration_hacker_01": "再生",
      "regeneration_happy_01": "再生",
      "regeneration_math_01": "再生",
      "regeneration_medical_01": "再生",
      "regeneration_science_01": "再生",
      "relief": "安心",
      "relief communication 01": "安心",
      "relief economy 01": "安心",
      "relief gag 01": "安心",
      "relief hacker 01": "安心",
      "relief happy 01": "安心",
      "relief math 01": "安心",
      "relief medical 01": "安心",
      "relief science 01": "安心",
      "relief-communication-01": "安心",
      "relief-economy-01": "安心",
      "relief-gag-01": "安心",
      "relief-hacker-01": "安心",
      "relief-happy-01": "安心",
      "relief-math-01": "安心",
      "relief-medical-01": "安心",
      "relief-science-01": "安心",
      "relief_communication_01": "安心",
      "relief_economy_01": "安心",
      "relief_gag_01": "安心",
      "relief_hacker_01": "安心",
      "relief_happy_01": "安心",
      "relief_math_01": "安心",
      "relief_medical_01": "安心",
      "relief_science_01": "安心",
      "resource": "資源",
      "resource communication 01": "資源",
      "resource economy 01": "資源",
      "resource gag 01": "資源",
      "resource hacker 01": "資源",
      "resource happy 01": "資源",
      "resource math 01": "資源",
      "resource medical 01": "資源",
      "resource science 01": "資源",
      "resource-communication-01": "資源",
      "resource-economy-01": "資源",
      "resource-gag-01": "資源",
      "resource-hacker-01": "資源",
      "resource-happy-01": "資源",
      "resource-math-01": "資源",
      "resource-medical-01": "資源",
      "resource-science-01": "資源",
      "resource_communication_01": "資源",
      "resource_economy_01": "資源",
      "resource_gag_01": "資源",
      "resource_hacker_01": "資源",
      "resource_happy_01": "資源",
      "resource_math_01": "資源",
      "resource_medical_01": "資源",
      "resource_science_01": "資源",
      "responsibility": "責任",
      "responsibility communication 01": "責任",
      "responsibility economy 01": "責任",
      "responsibility gag 01": "責任",
      "responsibility hacker 01": "責任",
      "responsibility happy 01": "責任",
      "responsibility math 01": "責任",
      "responsibility medical 01": "責任",
      "responsibility science 01": "責任",
      "responsibility-communication-01": "責任",
      "responsibility-economy-01": "責任",
      "responsibility-gag-01": "責任",
      "responsibility-hacker-01": "責任",
      "responsibility-happy-01": "責任",
      "responsibility-math-01": "責任",
      "responsibility-medical-01": "責任",
      "responsibility-science-01": "責任",
      "responsibility_communication_01": "責任",
      "responsibility_economy_01": "責任",
      "responsibility_gag_01": "責任",
      "responsibility_hacker_01": "責任",
      "responsibility_happy_01": "責任",
      "responsibility_math_01": "責任",
      "responsibility_medical_01": "責任",
      "responsibility_science_01": "責任",
      "risk": "リスク",
      "risk communication 01": "リスク",
      "risk economy 01": "リスク",
      "risk gag 01": "リスク",
      "risk hacker 01": "リスク",
      "risk happy 01": "リスク",
      "risk math 01": "リスク",
      "risk medical 01": "リスク",
      "risk science 01": "リスク",
      "risk-communication-01": "リスク",
      "risk-economy-01": "リスク",
      "risk-gag-01": "リスク",
      "risk-hacker-01": "リスク",
      "risk-happy-01": "リスク",
      "risk-math-01": "リスク",
      "risk-medical-01": "リスク",
      "risk-science-01": "リスク",
      "risk_communication_01": "リスク",
      "risk_economy_01": "リスク",
      "risk_gag_01": "リスク",
      "risk_hacker_01": "リスク",
      "risk_happy_01": "リスク",
      "risk_math_01": "リスク",
      "risk_medical_01": "リスク",
      "risk_science_01": "リスク",
      "rule": "ルール",
      "rule communication 01": "ルール",
      "rule economy 01": "ルール",
      "rule gag 01": "ルール",
      "rule hacker 01": "ルール",
      "rule happy 01": "ルール",
      "rule math 01": "ルール",
      "rule medical 01": "ルール",
      "rule science 01": "ルール",
      "rule-communication-01": "ルール",
      "rule-economy-01": "ルール",
      "rule-gag-01": "ルール",
      "rule-hacker-01": "ルール",
      "rule-happy-01": "ルール",
      "rule-math-01": "ルール",
      "rule-medical-01": "ルール",
      "rule-science-01": "ルール",
      "rule_communication_01": "ルール",
      "rule_economy_01": "ルール",
      "rule_gag_01": "ルール",
      "rule_hacker_01": "ルール",
      "rule_happy_01": "ルール",
      "rule_math_01": "ルール",
      "rule_medical_01": "ルール",
      "rule_science_01": "ルール",
      "sadness": "悲しみ",
      "sadness communication 01": "悲しみ",
      "sadness economy 01": "悲しみ",
      "sadness gag 01": "悲しみ",
      "sadness hacker 01": "悲しみ",
      "sadness happy 01": "悲しみ",
      "sadness math 01": "悲しみ",
      "sadness medical 01": "悲しみ",
      "sadness science 01": "悲しみ",
      "sadness-communication-01": "悲しみ",
      "sadness-economy-01": "悲しみ",
      "sadness-gag-01": "悲しみ",
      "sadness-hacker-01": "悲しみ",
      "sadness-happy-01": "悲しみ",
      "sadness-math-01": "悲しみ",
      "sadness-medical-01": "悲しみ",
      "sadness-science-01": "悲しみ",
      "sadness_communication_01": "悲しみ",
      "sadness_economy_01": "悲しみ",
      "sadness_gag_01": "悲しみ",
      "sadness_hacker_01": "悲しみ",
      "sadness_happy_01": "悲しみ",
      "sadness_math_01": "悲しみ",
      "sadness_medical_01": "悲しみ",
      "sadness_science_01": "悲しみ",
      "school lunch": "給食",
      "school lunch communication 01": "給食",
      "school lunch economy 01": "給食",
      "school lunch gag 01": "給食",
      "school lunch hacker 01": "給食",
      "school lunch happy 01": "給食",
      "school lunch math 01": "給食",
      "school lunch medical 01": "給食",
      "school lunch science 01": "給食",
      "school-lunch": "給食",
      "school-lunch-communication-01": "給食",
      "school-lunch-economy-01": "給食",
      "school-lunch-gag-01": "給食",
      "school-lunch-hacker-01": "給食",
      "school-lunch-happy-01": "給食",
      "school-lunch-math-01": "給食",
      "school-lunch-medical-01": "給食",
      "school-lunch-science-01": "給食",
      "school_lunch": "給食",
      "school_lunch_communication_01": "給食",
      "school_lunch_economy_01": "給食",
      "school_lunch_gag_01": "給食",
      "school_lunch_hacker_01": "給食",
      "school_lunch_happy_01": "給食",
      "school_lunch_math_01": "給食",
      "school_lunch_medical_01": "給食",
      "school_lunch_science_01": "給食",
      "secret": "ひみつ",
      "secret gag 01": "ひみつ",
      "secret hacker 01": "ひみつ",
      "secret math 01": "ひみつ",
      "secret-gag-01": "ひみつ",
      "secret-hacker-01": "ひみつ",
      "secret-math-01": "ひみつ",
      "secret_gag_01": "ひみつ",
      "secret_hacker_01": "ひみつ",
      "secret_math_01": "ひみつ",
      "sense": "感覚",
      "sense communication 01": "感覚",
      "sense economy 01": "感覚",
      "sense gag 01": "感覚",
      "sense hacker 01": "感覚",
      "sense happy 01": "感覚",
      "sense math 01": "感覚",
      "sense medical 01": "感覚",
      "sense science 01": "感覚",
      "sense-communication-01": "感覚",
      "sense-economy-01": "感覚",
      "sense-gag-01": "感覚",
      "sense-hacker-01": "感覚",
      "sense-happy-01": "感覚",
      "sense-math-01": "感覚",
      "sense-medical-01": "感覚",
      "sense-science-01": "感覚",
      "sense_communication_01": "感覚",
      "sense_economy_01": "感覚",
      "sense_gag_01": "感覚",
      "sense_hacker_01": "感覚",
      "sense_happy_01": "感覚",
      "sense_math_01": "感覚",
      "sense_medical_01": "感覚",
      "sense_science_01": "感覚",
      "silence": "沈黙",
      "silence communication 01": "沈黙",
      "silence economy 01": "沈黙",
      "silence gag 01": "沈黙",
      "silence hacker 01": "沈黙",
      "silence happy 01": "沈黙",
      "silence math 01": "沈黙",
      "silence medical 01": "沈黙",
      "silence science 01": "沈黙",
      "silence-communication-01": "沈黙",
      "silence-economy-01": "沈黙",
      "silence-gag-01": "沈黙",
      "silence-hacker-01": "沈黙",
      "silence-happy-01": "沈黙",
      "silence-math-01": "沈黙",
      "silence-medical-01": "沈黙",
      "silence-science-01": "沈黙",
      "silence_communication_01": "沈黙",
      "silence_economy_01": "沈黙",
      "silence_gag_01": "沈黙",
      "silence_hacker_01": "沈黙",
      "silence_happy_01": "沈黙",
      "silence_math_01": "沈黙",
      "silence_medical_01": "沈黙",
      "silence_science_01": "沈黙",
      "sky": "空",
      "sky communication 01": "空",
      "sky economy 01": "空",
      "sky gag 01": "空",
      "sky hacker 01": "空",
      "sky happy 01": "空",
      "sky math 01": "空",
      "sky medical 01": "空",
      "sky science 01": "空",
      "sky-communication-01": "空",
      "sky-economy-01": "空",
      "sky-gag-01": "空",
      "sky-hacker-01": "空",
      "sky-happy-01": "空",
      "sky-math-01": "空",
      "sky-medical-01": "空",
      "sky-science-01": "空",
      "sky_communication_01": "空",
      "sky_economy_01": "空",
      "sky_gag_01": "空",
      "sky_hacker_01": "空",
      "sky_happy_01": "空",
      "sky_math_01": "空",
      "sky_medical_01": "空",
      "sky_science_01": "空",
      "space": "空間",
      "space gag 01": "空間",
      "space hacker 01": "空間",
      "space math 01": "空間",
      "space-gag-01": "空間",
      "space-hacker-01": "空間",
      "space-math-01": "空間",
      "space_gag_01": "空間",
      "space_hacker_01": "空間",
      "space_math_01": "空間",
      "study": "勉強",
      "study communication 01": "勉強",
      "study economy 01": "勉強",
      "study gag 01": "勉強",
      "study hacker 01": "勉強",
      "study happy 01": "勉強",
      "study math 01": "勉強",
      "study medical 01": "勉強",
      "study science 01": "勉強",
      "study-communication-01": "勉強",
      "study-economy-01": "勉強",
      "study-gag-01": "勉強",
      "study-hacker-01": "勉強",
      "study-happy-01": "勉強",
      "study-math-01": "勉強",
      "study-medical-01": "勉強",
      "study-science-01": "勉強",
      "study_communication_01": "勉強",
      "study_economy_01": "勉強",
      "study_gag_01": "勉強",
      "study_hacker_01": "勉強",
      "study_happy_01": "勉強",
      "study_math_01": "勉強",
      "study_medical_01": "勉強",
      "study_science_01": "勉強",
      "success": "成功",
      "success communication 01": "成功",
      "success economy 01": "成功",
      "success gag 01": "成功",
      "success hacker 01": "成功",
      "success happy 01": "成功",
      "success math 01": "成功",
      "success medical 01": "成功",
      "success science 01": "成功",
      "success-communication-01": "成功",
      "success-economy-01": "成功",
      "success-gag-01": "成功",
      "success-hacker-01": "成功",
      "success-happy-01": "成功",
      "success-math-01": "成功",
      "success-medical-01": "成功",
      "success-science-01": "成功",
      "success_communication_01": "成功",
      "success_economy_01": "成功",
      "success_gag_01": "成功",
      "success_hacker_01": "成功",
      "success_happy_01": "成功",
      "success_math_01": "成功",
      "success_medical_01": "成功",
      "success_science_01": "成功",
      "supply": "供給",
      "supply communication 01": "供給",
      "supply economy 01": "供給",
      "supply gag 01": "供給",
      "supply hacker 01": "供給",
      "supply happy 01": "供給",
      "supply math 01": "供給",
      "supply medical 01": "供給",
      "supply science 01": "供給",
      "supply-communication-01": "供給",
      "supply-economy-01": "供給",
      "supply-gag-01": "供給",
      "supply-hacker-01": "供給",
      "supply-happy-01": "供給",
      "supply-math-01": "供給",
      "supply-medical-01": "供給",
      "supply-science-01": "供給",
      "supply_communication_01": "供給",
      "supply_economy_01": "供給",
      "supply_gag_01": "供給",
      "supply_hacker_01": "供給",
      "supply_happy_01": "供給",
      "supply_math_01": "供給",
      "supply_medical_01": "供給",
      "supply_science_01": "供給",
      "sweetness": "甘さ",
      "sweetness communication 01": "甘さ",
      "sweetness economy 01": "甘さ",
      "sweetness gag 01": "甘さ",
      "sweetness hacker 01": "甘さ",
      "sweetness happy 01": "甘さ",
      "sweetness math 01": "甘さ",
      "sweetness medical 01": "甘さ",
      "sweetness science 01": "甘さ",
      "sweetness-communication-01": "甘さ",
      "sweetness-economy-01": "甘さ",
      "sweetness-gag-01": "甘さ",
      "sweetness-hacker-01": "甘さ",
      "sweetness-happy-01": "甘さ",
      "sweetness-math-01": "甘さ",
      "sweetness-medical-01": "甘さ",
      "sweetness-science-01": "甘さ",
      "sweetness_communication_01": "甘さ",
      "sweetness_economy_01": "甘さ",
      "sweetness_gag_01": "甘さ",
      "sweetness_hacker_01": "甘さ",
      "sweetness_happy_01": "甘さ",
      "sweetness_math_01": "甘さ",
      "sweetness_medical_01": "甘さ",
      "sweetness_science_01": "甘さ",
      "teacher": "先生",
      "teacher communication 01": "先生",
      "teacher economy 01": "先生",
      "teacher gag 01": "先生",
      "teacher hacker 01": "先生",
      "teacher happy 01": "先生",
      "teacher math 01": "先生",
      "teacher medical 01": "先生",
      "teacher science 01": "先生",
      "teacher-communication-01": "先生",
      "teacher-economy-01": "先生",
      "teacher-gag-01": "先生",
      "teacher-hacker-01": "先生",
      "teacher-happy-01": "先生",
      "teacher-math-01": "先生",
      "teacher-medical-01": "先生",
      "teacher-science-01": "先生",
      "teacher_communication_01": "先生",
      "teacher_economy_01": "先生",
      "teacher_gag_01": "先生",
      "teacher_hacker_01": "先生",
      "teacher_happy_01": "先生",
      "teacher_math_01": "先生",
      "teacher_medical_01": "先生",
      "teacher_science_01": "先生",
      "test": "テスト",
      "test communication 01": "テスト",
      "test economy 01": "テスト",
      "test gag 01": "テスト",
      "test hacker 01": "テスト",
      "test happy 01": "テスト",
      "test math 01": "テスト",
      "test medical 01": "テスト",
      "test science 01": "テスト",
      "test-communication-01": "テスト",
      "test-economy-01": "テスト",
      "test-gag-01": "テスト",
      "test-hacker-01": "テスト",
      "test-happy-01": "テスト",
      "test-math-01": "テスト",
      "test-medical-01": "テスト",
      "test-science-01": "テスト",
      "test_communication_01": "テスト",
      "test_economy_01": "テスト",
      "test_gag_01": "テスト",
      "test_hacker_01": "テスト",
      "test_happy_01": "テスト",
      "test_math_01": "テスト",
      "test_medical_01": "テスト",
      "test_science_01": "テスト",
      "tickle": "くすぐったい",
      "tickle communication 01": "くすぐったい",
      "tickle economy 01": "くすぐったい",
      "tickle gag 01": "くすぐったい",
      "tickle hacker 01": "くすぐったい",
      "tickle happy 01": "くすぐったい",
      "tickle math 01": "くすぐったい",
      "tickle medical 01": "くすぐったい",
      "tickle science 01": "くすぐったい",
      "tickle-communication-01": "くすぐったい",
      "tickle-economy-01": "くすぐったい",
      "tickle-gag-01": "くすぐったい",
      "tickle-hacker-01": "くすぐったい",
      "tickle-happy-01": "くすぐったい",
      "tickle-math-01": "くすぐったい",
      "tickle-medical-01": "くすぐったい",
      "tickle-science-01": "くすぐったい",
      "tickle_communication_01": "くすぐったい",
      "tickle_economy_01": "くすぐったい",
      "tickle_gag_01": "くすぐったい",
      "tickle_hacker_01": "くすぐったい",
      "tickle_happy_01": "くすぐったい",
      "tickle_math_01": "くすぐったい",
      "tickle_medical_01": "くすぐったい",
      "tickle_science_01": "くすぐったい",
      "time": "時間",
      "time gag 01": "時間",
      "time hacker 01": "時間",
      "time math 01": "時間",
      "time-gag-01": "時間",
      "time-hacker-01": "時間",
      "time-math-01": "時間",
      "time_gag_01": "時間",
      "time_hacker_01": "時間",
      "time_math_01": "時間",
      "toy": "おもちゃ",
      "toy gag 01": "おもちゃ",
      "toy hacker 01": "おもちゃ",
      "toy math 01": "おもちゃ",
      "toy-gag-01": "おもちゃ",
      "toy-hacker-01": "おもちゃ",
      "toy-math-01": "おもちゃ",
      "toy_gag_01": "おもちゃ",
      "toy_hacker_01": "おもちゃ",
      "toy_math_01": "おもちゃ",
      "trace": "痕跡",
      "trace communication 01": "痕跡",
      "trace economy 01": "痕跡",
      "trace gag 01": "痕跡",
      "trace hacker 01": "痕跡",
      "trace happy 01": "痕跡",
      "trace math 01": "痕跡",
      "trace medical 01": "痕跡",
      "trace science 01": "痕跡",
      "trace-communication-01": "痕跡",
      "trace-economy-01": "痕跡",
      "trace-gag-01": "痕跡",
      "trace-hacker-01": "痕跡",
      "trace-happy-01": "痕跡",
      "trace-math-01": "痕跡",
      "trace-medical-01": "痕跡",
      "trace-science-01": "痕跡",
      "trace_communication_01": "痕跡",
      "trace_economy_01": "痕跡",
      "trace_gag_01": "痕跡",
      "trace_hacker_01": "痕跡",
      "trace_happy_01": "痕跡",
      "trace_math_01": "痕跡",
      "trace_medical_01": "痕跡",
      "trace_science_01": "痕跡",
      "traffic": "交通",
      "traffic communication 01": "交通",
      "traffic economy 01": "交通",
      "traffic gag 01": "交通",
      "traffic hacker 01": "交通",
      "traffic happy 01": "交通",
      "traffic math 01": "交通",
      "traffic medical 01": "交通",
      "traffic science 01": "交通",
      "traffic-communication-01": "交通",
      "traffic-economy-01": "交通",
      "traffic-gag-01": "交通",
      "traffic-hacker-01": "交通",
      "traffic-happy-01": "交通",
      "traffic-math-01": "交通",
      "traffic-medical-01": "交通",
      "traffic-science-01": "交通",
      "traffic_communication_01": "交通",
      "traffic_economy_01": "交通",
      "traffic_gag_01": "交通",
      "traffic_hacker_01": "交通",
      "traffic_happy_01": "交通",
      "traffic_math_01": "交通",
      "traffic_medical_01": "交通",
      "traffic_science_01": "交通",
      "translation": "翻訳",
      "translation communication 01": "翻訳",
      "translation economy 01": "翻訳",
      "translation gag 01": "翻訳",
      "translation hacker 01": "翻訳",
      "translation happy 01": "翻訳",
      "translation math 01": "翻訳",
      "translation medical 01": "翻訳",
      "translation science 01": "翻訳",
      "translation-communication-01": "翻訳",
      "translation-economy-01": "翻訳",
      "translation-gag-01": "翻訳",
      "translation-hacker-01": "翻訳",
      "translation-happy-01": "翻訳",
      "translation-math-01": "翻訳",
      "translation-medical-01": "翻訳",
      "translation-science-01": "翻訳",
      "translation_communication_01": "翻訳",
      "translation_economy_01": "翻訳",
      "translation_gag_01": "翻訳",
      "translation_hacker_01": "翻訳",
      "translation_happy_01": "翻訳",
      "translation_math_01": "翻訳",
      "translation_medical_01": "翻訳",
      "translation_science_01": "翻訳",
      "trust": "信頼",
      "trust communication 01": "信頼",
      "trust economy 01": "信頼",
      "trust gag 01": "信頼",
      "trust hacker 01": "信頼",
      "trust happy 01": "信頼",
      "trust math 01": "信頼",
      "trust medical 01": "信頼",
      "trust science 01": "信頼",
      "trust-communication-01": "信頼",
      "trust-economy-01": "信頼",
      "trust-gag-01": "信頼",
      "trust-hacker-01": "信頼",
      "trust-happy-01": "信頼",
      "trust-math-01": "信頼",
      "trust-medical-01": "信頼",
      "trust-science-01": "信頼",
      "trust_communication_01": "信頼",
      "trust_economy_01": "信頼",
      "trust_gag_01": "信頼",
      "trust_hacker_01": "信頼",
      "trust_happy_01": "信頼",
      "trust_math_01": "信頼",
      "trust_medical_01": "信頼",
      "trust_science_01": "信頼",
      "understanding": "理解",
      "understanding communication 01": "理解",
      "understanding economy 01": "理解",
      "understanding gag 01": "理解",
      "understanding hacker 01": "理解",
      "understanding happy 01": "理解",
      "understanding math 01": "理解",
      "understanding medical 01": "理解",
      "understanding science 01": "理解",
      "understanding-communication-01": "理解",
      "understanding-economy-01": "理解",
      "understanding-gag-01": "理解",
      "understanding-hacker-01": "理解",
      "understanding-happy-01": "理解",
      "understanding-math-01": "理解",
      "understanding-medical-01": "理解",
      "understanding-science-01": "理解",
      "understanding_communication_01": "理解",
      "understanding_economy_01": "理解",
      "understanding_gag_01": "理解",
      "understanding_hacker_01": "理解",
      "understanding_happy_01": "理解",
      "understanding_math_01": "理解",
      "understanding_medical_01": "理解",
      "understanding_science_01": "理解",
      "value": "価値",
      "value communication 01": "価値",
      "value economy 01": "価値",
      "value gag 01": "価値",
      "value hacker 01": "価値",
      "value happy 01": "価値",
      "value math 01": "価値",
      "value medical 01": "価値",
      "value science 01": "価値",
      "value-communication-01": "価値",
      "value-economy-01": "価値",
      "value-gag-01": "価値",
      "value-hacker-01": "価値",
      "value-happy-01": "価値",
      "value-math-01": "価値",
      "value-medical-01": "価値",
      "value-science-01": "価値",
      "value_communication_01": "価値",
      "value_economy_01": "価値",
      "value_gag_01": "価値",
      "value_hacker_01": "価値",
      "value_happy_01": "価値",
      "value_math_01": "価値",
      "value_medical_01": "価値",
      "value_science_01": "価値",
      "victory": "勝利",
      "victory communication 01": "勝利",
      "victory economy 01": "勝利",
      "victory gag 01": "勝利",
      "victory hacker 01": "勝利",
      "victory happy 01": "勝利",
      "victory math 01": "勝利",
      "victory medical 01": "勝利",
      "victory science 01": "勝利",
      "victory-communication-01": "勝利",
      "victory-economy-01": "勝利",
      "victory-gag-01": "勝利",
      "victory-hacker-01": "勝利",
      "victory-happy-01": "勝利",
      "victory-math-01": "勝利",
      "victory-medical-01": "勝利",
      "victory-science-01": "勝利",
      "victory_communication_01": "勝利",
      "victory_economy_01": "勝利",
      "victory_gag_01": "勝利",
      "victory_hacker_01": "勝利",
      "victory_happy_01": "勝利",
      "victory_math_01": "勝利",
      "victory_medical_01": "勝利",
      "victory_science_01": "勝利",
      "voice": "声",
      "voice gag 01": "声",
      "voice hacker 01": "声",
      "voice happy 01": "声",
      "voice math 01": "声",
      "voice-gag-01": "声",
      "voice-hacker-01": "声",
      "voice-happy-01": "声",
      "voice-math-01": "声",
      "voice_gag_01": "声",
      "voice_hacker_01": "声",
      "voice_happy_01": "声",
      "voice_math_01": "声",
      "word": "言葉",
      "word gag 01": "言葉",
      "word hacker 01": "言葉",
      "word math 01": "言葉",
      "word-gag-01": "言葉",
      "word-hacker-01": "言葉",
      "word-math-01": "言葉",
      "word_gag_01": "言葉",
      "word_hacker_01": "言葉",
      "word_math_01": "言葉"
    };
    if(map[s]) return map[s];
    return s.replace(/_/g, " ");
  }

  function displayTrack(s){
    s = String(s || "").trim();
    if(!s || s === "unknown") return "未分類";
    s = decodeURIComponent(s).split("/").pop().split("?")[0];
    s = s.replace(/\.(mp3|m4a|wav|ogg)$/i, "");

    try{
      var arr = (typeof musicPlaylists !== "undefined" && Array.isArray(musicPlaylists)) ? musicPlaylists :
                (window.musicPlaylists && Array.isArray(window.musicPlaylists) ? window.musicPlaylists : []);
      for(var i=0;i<arr.length;i++){
        var tracks = arr[i].tracks || [];
        for(var j=0;j<tracks.length;j++){
          var tr = tracks[j];
          var id = String(tr.id || "");
          var title = String(tr.title || "");
          var audio = String(tr.audio || "");
          if((id && s.indexOf(id) >= 0) || (audio && audio.indexOf(s) >= 0) || (title && s.indexOf(title) >= 0)){
            return title || id || s;
          }
        }
      }
    }catch(e){}

    return s.replace(/_/g, " ");
  }

  function topList(obj, max){
    return Object.keys(obj || {})
      .filter(function(k){ return k && k !== "unknown" && k !== "未分類" && Number(obj[k] || 0) > 0; })
      .sort(function(a,b){ return Number(obj[b] || 0) - Number(obj[a] || 0); })
      .slice(0, max || 5)
      .map(function(k){ return {key:k, value:Number(obj[k] || 0)}; });
  }

  function syntaxType(d){
    var ranks = topList(d.dictionary.megane, 4);
    if(!ranks.length) return "未観測";

    var total = ranks.reduce(function(a,x){ return a + x.value; }, 0);
    var top = ranks[0];
    var second = ranks[1] || { key:"", value:0 };
    var ratio = total ? top.value / total : 0;
    var gap = top.value - second.value;
    var defs = userDefinitionCount();
    var cardKinds = Number((d.cards && d.cards.kinds) || 0);
    var musicPlays = Number((d.music && d.music.plays) || 0);
    var confPlays = Number((d.conference && d.conference.plays) || 0);

    if(total < 3) return "観測中";

    // 書く人・広く遊ぶ人の特殊称号
    if(defs >= 100) return "辞書共犯者";
    if(defs >= 30) return "意味汚染型";
    if(defs >= 10) return "意味改変型";
    if(cardKinds >= 25) return "バインダー亡者";
    if(musicPlays >= 50) return "耳から観測型";
    if(confPlays >= 30) return "会議常駐型";

    // 拮抗・混合
    if(total >= 8 && ratio < 0.34) return "全方位観測型";
    if(total >= 8 && ratio < 0.45) return "多視点同期型";
    if(second.value > 0 && gap <= 1 && total >= 6) return "構文ゆらぎ型";

    var strong = ratio >= 0.70 || (top.value >= 8 && gap >= 4);
    var mid = ratio >= 0.50 || gap >= 2;

    var titles = {
      "ギャグメガネ": {
        strong: ["ズレ耐性Lv99", "世界を笑わせる側", "ボケ回収業者"],
        mid: ["ツッコミ待機型", "違和感収集家", "バグ許容型"],
        weak: ["ネタ発掘型", "笑い待ち"]
      },
      "ハッピーメガネ": {
        strong: ["希望過積載型", "全部大丈夫変換機", "幸せ誤検知型"],
        mid: ["跳ね待ち型", "可能性信者", "笑顔感染型"],
        weak: ["ふわふわ観測型", "やさしさ過多"]
      },
      "数学メガネ": {
        strong: ["未定義収集型", "定義厨", "関係式中毒"],
        mid: ["構造分析型", "証明保留型", "世界を式にしたい型"],
        weak: ["定義待ち", "構造好き"]
      },
      "ハッカーメガネ": {
        strong: ["例外処理型", "ログ監視型", "回避不能型"],
        mid: ["デバッグ脳", "バグ検知型", "システム侵入型"],
        weak: ["裏側気になる型", "監視中"]
      }
    };

    var set = titles[top.key];
    if(!set) return top.key + "型";

    var arr = strong ? set.strong : (mid ? set.mid : set.weak);
    // 同じ状態でも少し変化が出るように、観測回数で選ぶ
    var idx = Math.abs(total + top.value + defs + cardKinds) % arr.length;
    return arr[idx];
  }

  function daysSince(iso){
    try{ return Math.max(1, Math.ceil((Date.now() - new Date(iso).getTime()) / 86400000)); }
    catch(e){ return 1; }
  }

  function level(d){
    var exp = 0;
    exp += Number(d.dictionary.voices || 0) * 2;
    exp += Number(d.cards.kinds || 0) * 12;
    exp += Number(d.cards.draws || 0) * 3;
    exp += Number(d.music.plays || 0) * 3;
    exp += Number(d.music.completes || 0) * 10;
    exp += Number(d.conference.plays || 0) * 5;
    exp += Number(d.conference.completes || 0) * 12;
    exp += userDefinitionCount() * 8;
    return Math.max(1, Math.floor(Math.sqrt(exp / 18)) + 1);
  }

  function ensureStyle(){
    if(document.getElementById("observationLogPatchStyleV4")) return;
    var st = document.createElement("style");
    st.id = "observationLogPatchStyleV4";
    st.textContent = ""
      + ".obs-modal{position:fixed;inset:0;z-index:100000;display:grid;place-items:center;padding:max(18px,env(safe-area-inset-top)) 18px max(18px,env(safe-area-inset-bottom));background:rgba(0,0,0,.72);backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px)}"
      + ".obs-modal[hidden]{display:none!important}"
      + ".obs-card{width:min(92vw,460px);max-height:82vh;overflow:auto;border-radius:28px;border:1px solid rgba(255,230,170,.22);background:linear-gradient(145deg,rgba(48,31,26,.94),rgba(12,11,18,.96));color:#fff;padding:22px;box-shadow:0 24px 90px rgba(0,0,0,.65);-webkit-overflow-scrolling:touch}"
      + ".obs-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:16px}.obs-head strong{font-size:22px;letter-spacing:.06em}.obs-close{border-radius:999px;padding:8px 12px;font-weight:900}"
      + ".obs-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.obs-box{border:1px solid rgba(255,255,255,.10);border-radius:18px;background:rgba(255,255,255,.055);padding:13px}.obs-box span{display:block;font-size:12px;color:rgba(255,255,255,.58);font-weight:800}.obs-box b{display:block;margin-top:5px;font-size:22px;line-height:1.15}"
      + ".obs-section{margin-top:16px;padding-top:14px;border-top:1px solid rgba(255,255,255,.10)}.obs-mini-title{font-size:13px;color:rgba(255,255,255,.48);font-weight:900;margin:10px 0 4px}.obs-rank{display:flex;justify-content:space-between;gap:10px;padding:5px 0;font-weight:900;color:rgba(255,255,255,.82)}.obs-rank em{font-style:normal;color:rgba(255,230,170,.92)}"
      + ".obs-userdef{display:flex;justify-content:space-between;gap:12px;align-items:center;border:1px solid rgba(255,255,255,.10);background:rgba(255,255,255,.045);border-radius:16px;padding:11px 12px;margin-bottom:10px;font-weight:900}.obs-userdef span{color:rgba(255,255,255,.78)}.obs-userdef em{font-style:normal;color:rgba(255,230,170,.95)}"
      + ".obs-build{margin-top:18px;padding:14px 0 2px;text-align:center;color:rgba(255,255,255,.42);font-size:12px;font-weight:900;letter-spacing:.12em;user-select:none;-webkit-user-select:none}";
    document.head.appendChild(st);
  }

  function modal(id){
    ensureStyle();
    var m = document.getElementById(id);
    if(m) return m;
    m = document.createElement("div");
    m.id = id;
    m.className = "obs-modal";
    m.hidden = true;
    document.body.appendChild(m);
    m.addEventListener("click", function(e){ if(e.target === m) m.hidden = true; });
    return m;
  }

  function box(label, value){
    return '<div class="obs-box"><span>'+esc(label)+'</span><b>'+esc(value)+'</b></div>';
  }

  function rankHtml(title, list){
    var html = '<div class="obs-mini-title">'+esc(title)+'</div>';
    if(!list.length) return html + '<div class="obs-rank"><span>未観測</span><em>-</em></div>';
    list.forEach(function(item, i){
      html += '<div class="obs-rank"><span>'+(i+1)+'. '+esc(item.key)+'</span><em>×'+esc(item.value)+'</em></div>';
    });
    return html;
  }

  function userDefHtml(){
    var n = userDefinitionCount();
    return '<div class="obs-userdef"><span>✍ '+esc(userDefinitionTitle(n))+'</span><em>自分の定義 '+esc(n)+'件</em></div>';
  }

  function bindLongPress(el, fn, ms){
    if(!el || el.dataset.obsLongPressBound === "1") return;
    el.dataset.obsLongPressBound = "1";
    var timer = null;
    function start(e){ clearTimeout(timer); timer = setTimeout(function(){ fn(e); }, ms || LONG_MS); }
    function end(){ clearTimeout(timer); timer = null; }
    el.addEventListener("pointerdown", start, true);
    el.addEventListener("pointerup", end, true);
    el.addEventListener("pointerleave", end, true);
    el.addEventListener("pointercancel", end, true);
    el.addEventListener("touchstart", start, true);
    el.addEventListener("touchend", end, true);
    el.addEventListener("touchcancel", end, true);
  }

  function showLog(){
    var d = load();
    refreshCardStats(d);
    save(d);

    var meganeRanks = topList(d.dictionary.megane, 4);
    var wordRanks = topList(d.dictionary.words, 3);
    var trackRanks = topList(d.music.tracks, 3);

    var m = modal("observationLogModal");
    m.innerHTML = ''
      + '<div class="obs-card">'
      + '<div class="obs-head"><strong>👁 観測ログ</strong><button class="obs-close" data-close>×</button></div>'
      + '<div class="obs-grid">'
      + box("観測レベル", "Lv." + level(d))
      + box("観測日数", daysSince(d.createdAt) + "日")
      + box("カード種類", (d.cards.kinds || 0) + " / 25")
      + box("総所持カード", (d.cards.total || 0) + "枚")
      + box("辞書観測", d.dictionary.voices || 0)
      + box("構文タイプ", syntaxType(d))
      + box("音楽再生", d.music.plays || 0)
      + box("Conference", d.conference.plays || 0)
      + '</div>'
      + '<div class="obs-section">'
      + userDefHtml()
      + rankHtml("よく観測するメガネ", meganeRanks)
      + rankHtml("よく見る単語", wordRanks)
      + rankHtml("よく聴く曲", trackRanks)
      + '<div class="obs-mini-title">最近の観測</div>'
      + '<div class="obs-rank"><span>まだありません</span><em>-</em></div>'
      + '</div>'
      + '<div class="obs-section" style="color:rgba(255,255,255,.58);font-size:12px;line-height:1.7;font-weight:800;">ここは、あなたが観測した世界の記録です。</div>'
      + '<div class="obs-build" id="obsBuildLabel">Build 1.0.3</div>'
      + '</div>';
    m.hidden = false;
    m.querySelector("[data-close]").onclick = function(){ m.hidden = true; };

    var build = document.getElementById("obsBuildLabel");
    if(build){
      build.dataset.obsLongPressBound = "";
      bindLongPress(build, function(){
        if(window.MEGANE_DEVELOPER_OPEN) window.MEGANE_DEVELOPER_OPEN();
      }, 1100);
    }
  }

  function findLogo(){
    var nodes = Array.prototype.slice.call(document.querySelectorAll("div,span,h1,h2,p,button"));
    return nodes.find(function(x){ return (x.textContent || "").trim() === "MEGANE DICTIONARY"; });
  }

  function autoBind(){
    var logo = findLogo();
    if(logo) bindLongPress(logo, function(){ observe("status.open"); showLog(); });
  }

  function boot(){
    observe("app.open");
    autoBind();
    setInterval(autoBind, 1000);
  }

  window.MEGANE_OBSERVE = observe;
  window.MEGANE_OBSERVATION_LOG = {
    load: load,
    save: save,
    observe: observe,
    show: showLog,
    userDefinitionCount: userDefinitionCount,
    syntaxType: function(){ return syntaxType(load()); },
    refreshCardStats: function(){ var d=load(); refreshCardStats(d); save(d); return d; },
    reset: function(){ localStorage.removeItem(LOG_KEY); observe("app.open"); }
  };

  if(document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot);
  else boot();
})();
